<html>

  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/Project/static/css/history1.css">
  <title>About Us</title>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
  <style>
      html {
  scroll-behavior: smooth;
}

  </style>
  </head>

  <body>

    <?php include('nav.php'); ?>

    <h2 style="text-align:center; font-size: 27px;margin:50px 20px; font-weight:lighter;">Iconic Paintings In The History Of Art</h2>
    <div class="history">
      <div class="historyof">
        <div class="historyimg" id="monalisa"></div>
        <div class="historytext">
          <h3>The Mona Lisa</h3>
          <p>Mona Lisa, also called Portrait of Lisa Gherardini, wife of Francesco is an oil painting on a poplar wood panel by Leonardo da Vinci, probably the world’s most famous painting.It was painted sometime between 1503 and 1519, when Leonardo was living in Florence, and it now hangs in the Louvre Museum, in Paris, where it remained an object of pilgrimage in the 21st century. The sitter’s mysterious smile and her unproven identity have made the painting a source of ongoing investigation and fascination.The painting presents a woman in half-body portrait, which has as a backdrop a distant landscape. Yet this simple description of a seemingly standard composition gives little sense of Leonardo’s achievement.</p>
        </div>
      </div>

      <div class="historyof">
        <div class="historyimg" id="irises"></div>
        <div class="historytext">
          <h3>Irises</h3>
          <p>In May 1889, after episodes of self-mutilation and hospitalization, Vincent van Gogh chose to enter an asylum in Saint-Rémy, France. There, in the last year before his death, he created almost 130 paintings. Within the first week, he began Irises, working from nature in the asylum's garden. The cropped composition, divided into broad areas of vivid color with monumental irises overflowing its borders, was probably influenced by the decorative patterning of Japanese woodblock prints.</p>
        </div>
      </div>

      <div class="historyof" >
        <div class="historyimg" id="starrynight"></div>
        <div class="historytext">
        <h3>The Starry Night</h3>
        <p>The Starry Night is based on van Gogh’s direct observations as well as his imagination, memories, and emotions. The steeple of the church, for example, resembles those common in his native Holland, not in France. The whirling forms in the sky, on the other hand, match published astronomical observations of clouds of dust and gas known as nebulae.The composition is structured by his ordered placement of the cypress, steeple, and central nebulae, while his countless short brushstrokes and thickly applied paint set its surface in roiling motion. Such a combination of visual contrasts was generated by an artist who found beauty and interest in the night, which, for him, was “much more alive and richly colored than the day"</p>
        </div>
      </div>

      <div class="historyof">
        <div class="historyimg" id="thescream"></div>
        <div class="historytext">
        <h3>The Scream</h3>
        <p>The Scream is autobiographical, an expressionistic construction based on Munch's actual experience of a scream piercing through nature while on a walk, after his two companions, seen in the background, had left him. Fitting the fact that the sound must have been heard at a time when his mind was in an abnormal state,
          Munch renders it in a style which if pushed to extremes can destroy human integrity.
          As previously noted, the flowing curves of art nouveau represent a subjective linear fusion imposed upon nature, whereby the multiplicity of particulars is unified into a totality of organic suggestion with feminine overtones. But man is part of nature, and absorption into such a totality liquidates the individual.</p>
        </div>
      </div><br><br>
    </div>



    <?php include ('footer.php');?>

  </body>
</html>
